# Generated by Django 3.2.13 on 2023-03-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_first_name_user_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='city',
        ),
    ]
