# Generated by Django 4.1.4 on 2023-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(default='users/passports/logo.png', upload_to='users/passports/'),
        ),
    ]
