# Generated by Django 4.1.4 on 2023-05-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='users/passports/logo.png', upload_to='users/passports/'),
        ),
    ]
