# Generated by Django 3.2.13 on 2023-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('time', models.TimeField(auto_now=True)),
                ('counts', models.IntegerField(default=0)),
            ],
        ),
    ]
