# Generated by Django 3.2.13 on 2023-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, editable=False, max_length=200)),
                ('link', models.CharField(blank=True, editable=False, max_length=200)),
            ],
        ),
    ]
