# Generated by Django 3.2.13 on 2023-04-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(blank=True, editable=False, max_length=200)),
                ('baths', models.CharField(blank=True, editable=False, max_length=200)),
                ('area', models.CharField(blank=True, editable=False, max_length=200)),
                ('price', models.IntegerField(blank=True, editable=False, max_length=200)),
                ('title', models.CharField(blank=True, editable=False, max_length=200)),
                ('coverPhoto', models.CharField(blank=True, editable=False, max_length=200)),
                ('state', models.CharField(blank=True, editable=False, max_length=200)),
                ('rentType', models.CharField(blank=True, editable=False, max_length=200)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
