# Generated by Django 3.2.13 on 2023-04-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to='properties/passports/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
