# Generated by Django 3.2.13 on 2023-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20230406_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.ImageField(blank=True, upload_to='properties/passports/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
