# Generated by Django 4.1.4 on 2023-05-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20230422_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('friends', 'Friends'), ('public', 'Public')], max_length=200)),
                ('policy', models.CharField(default='Posted property is owned by the posted user', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='privacy',
            field=models.ForeignKey(default='here we go', on_delete=django.db.models.deletion.CASCADE, to='properties.privacy'),
            preserve_default=False,
        ),
    ]
