# Generated by Django 4.1.4 on 2023-05-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_privacy_property_description_property_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='privacy',
        ),
    ]
