# Generated by Django 4.1.4 on 2023-05-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_area_remove_property_baths_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='privacy',
        ),
    ]
