# Generated by Django 4.1.4 on 2023-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_delete_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('friends', 'Friends'), ('public', 'Public')], max_length=200)),
                ('policy', models.CharField(default='Posted property is owned by the posted user', max_length=200)),
            ],
        ),
    ]
