# Generated by Django 4.1.4 on 2023-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_area_property_baths_property_coverphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
