# Generated by Django 4.1.4 on 2023-05-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_property_area_remove_property_baths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to='properties/passports/'),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.ImageField(blank=True, upload_to='properties/passports/'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='privacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.privacy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rentType',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
