# Generated by Django 4.1.4 on 2023-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_remove_property_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
