# Generated by Django 4.1.4 on 2023-05-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_property_area_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='property',
            name='coverPhoto',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rentType',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
    ]
