# Generated by Django 4.1.4 on 2023-05-29 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_remove_property_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='privacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.privacy'),
            preserve_default=False,
        ),
    ]
