# Generated by Django 4.1.4 on 2023-05-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_remove_property_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
