# Generated by Django 4.1.4 on 2023-05-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_reactions_comments_reactions_flags_reactions_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flags',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
