# Generated by Django 4.1.4 on 2023-05-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_delete_flags_delete_likes_delete_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='shares',
        ),
    ]
