# Generated by Django 4.1.4 on 2023-05-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_reactions_flags_reactions_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='property',
        ),
    ]
