# Generated by Django 4.1.4 on 2023-05-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_reactions_propert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='propert',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='shares',
        ),
    ]
