# Generated by Django 4.1.4 on 2023-05-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_remove_reactions_comments_remove_reactions_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reactions',
            name='flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reactions',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reactions',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactions',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
