# Generated by Django 4.1.4 on 2023-05-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_reactions_comments_reactions_flags_reactions_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='property',
        ),
        migrations.RemoveField(
            model_name='reactions',
            name='shares',
        ),
    ]
