# Generated by Django 4.1.4 on 2023-05-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_reactions_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactions',
            name='comments',
        ),
    ]
