# Generated by Django 4.1.4 on 2023-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_remove_reactions_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
