# Generated by Django 4.1.4 on 2023-05-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_reactions_flags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reactions',
        ),
    ]
