# Generated by Django 4.1.4 on 2023-05-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0052_comment_agent_comment_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.comment'),
            preserve_default=False,
        ),
    ]
